"""
01_inspect_data.py
-------------------
Inspects all raw Olist CSV files: shape, dtypes, null counts, sample rows.
Run this first to understand the raw data before loading into SQLite.

Usage: python 01_inspect_data.py
"""
import pandas as pd
import os

RAW_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "raw")
LOG_PATH = os.path.join(os.path.dirname(__file__), "..", "logs", "01_data_inspection.log")

FILES = {
    "customers": "customers.csv",
    "geolocation": "geolocation.csv",
    "order_items": "order_items.csv",
    "order_payments": "order_payments.csv",
    "order_reviews": "order_reviews.csv",
    "orders": "orders.csv",
    "products": "products.csv",
    "sellers": "sellers.csv",
    "category_translation": "category_translation.csv",
}

def inspect_file(name, path, log):
    df = pd.read_csv(path)
    log.write(f"\n{'='*70}\n")
    log.write(f"TABLE: {name}\n")
    log.write(f"{'='*70}\n")
    log.write(f"Shape: {df.shape[0]:,} rows x {df.shape[1]} columns\n\n")
    log.write("Columns & dtypes:\n")
    log.write(df.dtypes.to_string() + "\n\n")
    log.write("Null counts:\n")
    nulls = df.isnull().sum()
    nulls = nulls[nulls > 0]
    if len(nulls) > 0:
        log.write(nulls.to_string() + "\n\n")
    else:
        log.write("No nulls.\n\n")
    log.write("Duplicate rows: " + str(df.duplicated().sum()) + "\n\n")
    log.write("Sample (first 3 rows):\n")
    log.write(df.head(3).to_string() + "\n")
    print(f"[OK] {name}: {df.shape[0]:,} rows x {df.shape[1]} cols")
    return df.shape

def main():
    os.makedirs(os.path.dirname(LOG_PATH), exist_ok=True)
    summary = {}
    with open(LOG_PATH, "w", encoding="utf-8") as log:
        log.write("OLIST DATA INSPECTION LOG\n")
        log.write("Generated by 01_inspect_data.py\n")
        for name, fname in FILES.items():
            path = os.path.join(RAW_DIR, fname)
            shape = inspect_file(name, path, log)
            summary[name] = shape

        log.write(f"\n{'='*70}\n")
        log.write("SUMMARY\n")
        log.write(f"{'='*70}\n")
        for name, shape in summary.items():
            log.write(f"{name:25s} {shape[0]:>10,} rows x {shape[1]:>3} cols\n")

    print(f"\nFull inspection log written to: {LOG_PATH}")

if __name__ == "__main__":
    main()
