"""
02_load_to_sqlite.py
---------------------
Loads all raw Olist CSVs into a SQLite database, AS-IS (no cleaning/transformation).
Cleaning and transformation happens in SQL scripts (sql/ folder), not here —
this script's only job is raw ingestion so the .sql files are the visible,
auditable "work" for the portfolio.

Usage: python 02_load_to_sqlite.py
"""
import pandas as pd
import sqlite3
import os

RAW_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "raw")
DB_PATH = os.path.join(os.path.dirname(__file__), "..", "db", "olist.db")
LOG_PATH = os.path.join(os.path.dirname(__file__), "..", "logs", "02_load_to_sqlite.log")

# Maps raw_table_name -> csv filename
TABLES = {
    "raw_customers": "customers.csv",
    "raw_geolocation": "geolocation.csv",
    "raw_order_items": "order_items.csv",
    "raw_order_payments": "order_payments.csv",
    "raw_order_reviews": "order_reviews.csv",
    "raw_orders": "orders.csv",
    "raw_products": "products.csv",
    "raw_sellers": "sellers.csv",
    "raw_category_translation": "category_translation.csv",
}

def main():
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    os.makedirs(os.path.dirname(LOG_PATH), exist_ok=True)

    # Start fresh every run — idempotent
    if os.path.exists(DB_PATH):
        os.remove(DB_PATH)

    conn = sqlite3.connect(DB_PATH)
    log_lines = ["OLIST SQLITE LOAD LOG", "Generated by 02_load_to_sqlite.py", ""]

    for table_name, fname in TABLES.items():
        csv_path = os.path.join(RAW_DIR, fname)
        df = pd.read_csv(csv_path)
        df.to_sql(table_name, conn, if_exists="replace", index=False)
        line = f"[OK] Loaded {table_name:30s} <- {fname:30s} ({df.shape[0]:,} rows, {df.shape[1]} cols)"
        print(line)
        log_lines.append(line)

    # Verify row counts match by querying back
    log_lines.append("\nVerification (row counts from SQLite):")
    cur = conn.cursor()
    for table_name in TABLES:
        cur.execute(f"SELECT COUNT(*) FROM {table_name}")
        count = cur.fetchone()[0]
        log_lines.append(f"  {table_name:30s} {count:>10,} rows")

    conn.close()

    with open(LOG_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(log_lines))

    print(f"\nDatabase created at: {DB_PATH}")
    print(f"Load log written to: {LOG_PATH}")

if __name__ == "__main__":
    main()
