"""
03_run_sql.py
--------------
Executes all SQL scripts in sql/ against db/olist.db, in order.
This is the single command to (re)build every view after raw data
changes or SQL scripts are edited. Idempotent - all views use
DROP VIEW IF EXISTS before CREATE VIEW.

Usage: python 03_run_sql.py
"""
import sqlite3
import os
import time

SQL_DIR = os.path.join(os.path.dirname(__file__), "..", "sql")
DB_PATH = os.path.join(os.path.dirname(__file__), "..", "db", "olist.db")
LOG_PATH = os.path.join(os.path.dirname(__file__), "..", "logs", "03_run_sql.log")

# Run in this explicit order - later scripts depend on earlier ones
SQL_SCRIPTS = [
    "01_cleaning.sql",
    "02_sales_analysis.sql",
    "03_logistics_analysis.sql",
    "04_customer_reviews.sql",
]

def main():
    conn = sqlite3.connect(DB_PATH)
    log_lines = ["SQL EXECUTION LOG", "Generated by 03_run_sql.py", ""]

    for script_name in SQL_SCRIPTS:
        path = os.path.join(SQL_DIR, script_name)
        with open(path, "r", encoding="utf-8") as f:
            script = f.read()
        t0 = time.time()
        conn.executescript(script)
        conn.commit()
        elapsed = time.time() - t0
        line = f"[OK] {script_name:30s} executed in {elapsed:.2f}s"
        print(line)
        log_lines.append(line)

    # List all views now present
    cur = conn.cursor()
    cur.execute("SELECT name FROM sqlite_master WHERE type='view' ORDER BY name")
    views = [r[0] for r in cur.fetchall()]
    log_lines.append(f"\nTotal views in database: {len(views)}")
    for v in views:
        log_lines.append(f"  - {v}")

    conn.close()

    os.makedirs(os.path.dirname(LOG_PATH), exist_ok=True)
    with open(LOG_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(log_lines))

    print(f"\nAll SQL scripts executed. {len(views)} views created.")
    print(f"Log written to: {LOG_PATH}")

if __name__ == "__main__":
    main()
