"""
04_export_views.py
--------------------
Exports each analysis-ready SQL view to a Parquet file under
data/processed/. The Streamlit dashboard reads ONLY from these
Parquet files, never from db/olist.db directly - this fully decouples
the app from the database, avoiding SQLite file-locking/concurrency
concerns on Streamlit Cloud and giving faster app cold-starts.

Re-run this script any time the SQL views change or raw data is
refreshed, to keep the Parquet exports in sync.

Usage: python 04_export_views.py
"""
import sqlite3
import pandas as pd
import os

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "db", "olist.db")
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "processed")
LOG_PATH = os.path.join(os.path.dirname(__file__), "..", "logs", "04_export_views.log")

# Only export analysis-ready views meant for the dashboard.
# clean_* views are intermediate/base layer (used to build the views
# below); _geo_avg / _geo_mode are internal helpers - neither is
# exported since the dashboard only needs the final aggregated views.
VIEWS_TO_EXPORT = [
    # Page 1: Sales & Revenue
    "sales_monthly_trend",
    "sales_by_category",
    "sales_by_state",
    "sales_payment_breakdown",
    # Page 2: Delivery Performance
    "logistics_delivery_by_state",
    "logistics_delay_distribution",
    "logistics_freight_ratio",
    "logistics_route_performance",
    # Page 3: Customer Experience
    "reviews_score_distribution",
    "reviews_score_by_delay",
    "reviews_score_by_category",
    "reviews_score_by_payment",
]

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    log_lines = ["VIEW EXPORT LOG", "Generated by 04_export_views.py", ""]

    for view_name in VIEWS_TO_EXPORT:
        df = pd.read_sql(f"SELECT * FROM {view_name}", conn)
        out_path = os.path.join(OUT_DIR, f"{view_name}.parquet")
        df.to_parquet(out_path, index=False)
        size_kb = os.path.getsize(out_path) / 1024
        line = f"[OK] {view_name:35s} -> {view_name}.parquet  ({df.shape[0]:,} rows, {size_kb:.1f} KB)"
        print(line)
        log_lines.append(line)

    conn.close()

    with open(LOG_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(log_lines))

    print(f"\n{len(VIEWS_TO_EXPORT)} views exported to: {OUT_DIR}")
    print(f"Log written to: {LOG_PATH}")

if __name__ == "__main__":
    main()
